### ISSUE TITLE
[Bug]: VideosListResponse has no attribute 'context' at ['received_data']['context']

### ISSUE THREAD

**Issue by WilliamMayor** [apivideo/api.video-python-client#94] opened 2024-06-30 15:01 UTC
### Version

1.3.1

### Environment that reproduces the issue

Python 3.11

### Is it reproducible in the example application?

Yes

### Reproduction steps

Try to list videos using `VideosApi(client).list(...)`

### Expected result

Get a list of video data.

### Actual result

Get an exception: VideosListResponse has no attribute 'context' at ['received_data']['context']

### Additional context

I'm not trying to interact with received_data or context, these are dict lookups that the library is performing.

I can see from debug tools that the data is being returned.

### Relevant logs output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/ite/bootcamp/views.py", line 146, in bootcamp
    video = stream.get_recording(bootcamp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/ite/bootcamp/stream.py", line 32, in get_recording
    resp = api.list(
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apivideo/api/videos_api.py", line 1329, in list
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apivideo/api_client.py", line 422, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apivideo/api_client.py", line 245, in __call_api
    return_data = self.deserialize(
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apivideo/api_client.py", line 342, in deserialize
    deserialized_data = validate_and_convert_types(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apivideo/model_utils.py", line 1420, in validate_and_convert_types
    converted_instance = attempt_convert_item(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apivideo/model_utils.py", line 1307, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apivideo/model_utils.py", line 1227, in deserialize_model
    return model_class(**kw_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apivideo/model_utils.py", line 1592, in wrapped_init
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apivideo/model/videos_list_response.py", line 179, in __init__
    setattr(self, var_name, var_value)
  File "/usr/local/lib/python3.11/site-packages/apivideo/model_utils.py", line 191, in __setattr__
    self[attr] = value
    ~~~~^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apivideo/model_utils.py", line 376, in __setitem__
    self.set_attribute(name, value)
  File "/usr/local/lib/python3.11/site-packages/apivideo/model_utils.py", line 140, in set_attribute
    raise ApiAttributeError(
apivideo.exceptions.ApiAttributeError: VideosListResponse has no attribute 'context' at ['received_data']['context']
```

**Comment by olivierapivideo** [comment] 2024-07-01 14:12
Hey @WilliamMayor 

Thank you for reporting this issue, and we apologize for the inconvenience caused. The issue is fixed in version 1.3.2. Please update and try again.

Regards

**Closed by olivierapivideo** 2024-07-01 14:12 UTC
Labels: bug
